### ISSUE TITLE
Technical Report

### ISSUE THREAD

**Issue by fletchy95** [fletchy95/Agrivolution#22]
Similar to SRS document please mark here when you have finished your portion of the document, proof read it, and are ok with submitting the document.  When everyone has marked down here I will go ahead and submit the document.

**Comment by fletchy95** [comment]
I have finished with the report.  @Evelynfeifei have you finished?

**Comment by Evelynfeifei** [comment]
Yeah, I have finished it. I also reorganized it to a better structure.
Please check it out and add something for the appendices. Thanks!

**Comment by fletchy95** [comment]
@VandanaVenkatRaman @ImmaBicBoi please review the document and comment here when if you are satisfied for that version to be submitted.

**Comment by VandanaVenkatRaman** [comment]
Great work Yifei and Jack!! I reviewed it and it looks perfectly fine to me.. Good job guys!

**Comment by fletchy95** [comment]
Uploaded.
