### ISSUE TITLE
Final Report

### ISSUE THREAD

**Issue by fletchy95** [fletchy95/Agrivolution#44]
Keep in mind we need to create a final report.  I will contact our advisors and Professor Ramsey on details as to what this Final report shall contain.  Any future information will be posted here.

**Comment by fletchy95** [comment]
We will also mark in here when we approve of submission of this final document.

**Comment by fletchy95** [comment]
Followed up with professor in class and the final report will be the exact same sections as last semesters "final report" we just need to adjust it accordingly to this semester and add a section about Testing.  I will have official section list below.

**Comment by fletchy95** [comment]
@Evelynfeifei @VandanaVenkatRaman @ImmaBicBoi 
Sections Required:
    INTRODUCTION
    AIM
    BACKGROUND
    TECHNICAL CONTENT
    TESTING
    CONCLUSIONS
    EVALUATION AND REFLECTION

Some of these sections we may be able to mostly take from last semester, some will need adjustments and Testing needs to be written.  For testing we just say how we tested our product, and proved that it works as expected.

**Comment by Evelynfeifei** [comment]
I have added a section called main functionalities in Technical content. I also have finished my heatmap part.

**Comment by fletchy95** [comment]
@VandanaVenkatRaman @ImmaBicBoi requires your approval

**Comment by VandanaVenkatRaman** [comment]
I added a section with the steps to link the app to the firebase. I am good with the document. Green signal from my end !!
