### ISSUE TITLE
Final Presentation

### ISSUE THREAD

**Issue by fletchy95** [fletchy95/Agrivolution#49]
Final presentation is scheduled for next week on April 24th.  I'll start building our presentation slides however I think we should use our same layout as last semester but we should be able to skip the wireframe demo.

**Comment by fletchy95** [comment]
Chance the presentation will be moved to May 1st.  Professor Ramsey said he would email us to notify.

**Comment by Evelynfeifei** [comment]
I have reviewed the master branch and test it on my computer. Everything is fine.

**Comment by fletchy95** [comment]
presentation slides are complete all we gotta do is present.  Leaving issue open until presentation is complete.
